-- STREAMING_CHUNK:Configurando el propósito del script y filtrando la población por línea de crédito...
-- ============================================================
-- PROPÓSITO: REPORTE DE NÚMERO DE COMPRAS PROMEDIO AL CABO DE 2 AÑOS (MOB 24)
-- UTILIZANDO LA VARIABLE DE COMPRAS ACUMULADAS (CTA_NUM_CMP_LTD)
-- SEGMENTADO POR BURÓ HIT Y RANGO DE LÍNEA DE CRÉDITO
-- POBLACIÓN: BR_ORG = 210, CUENTAS VÁLIDAS
-- ============================================================

-- STREAMING_CHUNK:Filtrando el universo de solicitudes por canal y fechas activas...
WITH SOLICITUDES AS (
  SELECT
    a.CTA_CVE,
    a.BR_HIT_DES
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VMASTER.VFAC_NEGFIN_SOLICITUDES` a
  WHERE a.DT_FCH_SOL BETWEEN '2024-11-01' AND '2025-10-31'  -- Rango temporal de solicitudes
    AND a.BR_ORG = 200                                       -- Filtro de producto
    AND a.CTA_CVE > 0                                        -- Cuentas válidas
),

-- STREAMING_CHUNK:Obteniendo el historial de compras LTD (CTA_NUM_CMP_LTD) mes a mes por cuenta...
HISTORICO_SDO AS (
  SELECT
    a.CTA_CVE,
    a.CTA_NUM_CMP_LTD, -- Número de compras acumuladas Life-To-Date
    a.CTA_IMP_LIM_CRD, -- Límite de crédito registrado
    DATE_DIFF(DATE(a.ANIO, a.MES, 1), DATE_TRUNC(b.CTA_FCH_ALTA, MONTH), MONTH) AS MOB
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_SDO_CTA_MES` a
  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA` b
    ON a.CTA_CVE = b.CTA_CVE
  WHERE a.TIP_INF = 200
    AND a.CTA_EDO_CVE NOT IN ('T', 'P', 'Z', '8', '9')
    AND a.ANIO >= 2024
),

-- STREAMING_CHUNK:Pivoteando las compras LTD acumuladas del mes 1 al mes 24 (2 años en libros)...
COMPORTAMIENTO_CUENTAS AS (
  SELECT
    CTA_CVE,
    -- Límite de crédito base obtenido al inicio (MOB <= 1 o Máximo)
    COALESCE(
      MAX(CASE WHEN MOB <= 1 THEN CTA_IMP_LIM_CRD END),
      MAX(CTA_IMP_LIM_CRD)
    ) AS CTA_IMP_LIM_CRD,

    -- Compras acumuladas (CTA_NUM_CMP_LTD) mes a mes hasta el año 2 (MOB 24)
    MAX(CASE WHEN MOB = 1 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_1M,
    MAX(CASE WHEN MOB = 2 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_2M,
    MAX(CASE WHEN MOB = 3 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_3M,
    MAX(CASE WHEN MOB = 4 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_4M,
    MAX(CASE WHEN MOB = 5 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_5M,
    MAX(CASE WHEN MOB = 6 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_6M,
    MAX(CASE WHEN MOB = 7 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_7M,
    MAX(CASE WHEN MOB = 8 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_8M,
    MAX(CASE WHEN MOB = 9 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_9M,
    MAX(CASE WHEN MOB = 10 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_10M,
    MAX(CASE WHEN MOB = 11 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_11M,
    MAX(CASE WHEN MOB = 12 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_12M,
    MAX(CASE WHEN MOB = 13 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_13M,
    MAX(CASE WHEN MOB = 14 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_14M,
    MAX(CASE WHEN MOB = 15 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_15M,
    MAX(CASE WHEN MOB = 16 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_16M,
    MAX(CASE WHEN MOB = 17 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_17M,
    MAX(CASE WHEN MOB = 18 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_18M,
    MAX(CASE WHEN MOB = 19 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_19M,
    MAX(CASE WHEN MOB = 20 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_20M,
    MAX(CASE WHEN MOB = 21 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_21M,
    MAX(CASE WHEN MOB = 22 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_22M,
    MAX(CASE WHEN MOB = 23 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_23M,
    MAX(CASE WHEN MOB = 24 THEN CTA_NUM_CMP_LTD END) AS NUM_CMP_LTD_24M -- Al cabo de 2 Años
  FROM HISTORICO_SDO
  WHERE MOB BETWEEN 1 AND 24
  GROUP BY CTA_CVE
),

-- STREAMING_CHUNK:Consolidando solicitudes y asignando segmentos de línea de crédito...
CONSOLIDADO AS (
  SELECT
    sol.BR_HIT_DES,
    sol.CTA_CVE,
    cmp.CTA_IMP_LIM_CRD,

    -- Asignación de Segmento / Rango de Línea de Crédito
    CASE 
      WHEN cmp.CTA_IMP_LIM_CRD <= 4000 THEN '01. 0-4000'
      WHEN cmp.CTA_IMP_LIM_CRD BETWEEN 4001 AND 8000 THEN '02. 4001-8000'
      WHEN cmp.CTA_IMP_LIM_CRD BETWEEN 8001 AND 12000 THEN '03. 8001-12000'
      WHEN cmp.CTA_IMP_LIM_CRD BETWEEN 12001 AND 16000 THEN '04. 12001-16000'
      WHEN cmp.CTA_IMP_LIM_CRD BETWEEN 16001 AND 20000 THEN '05. 16001-20000'
      WHEN cmp.CTA_IMP_LIM_CRD > 20000 THEN '06. 20000+'
      ELSE '07. NO IDENTIFICADO'
    END AS RANGO_LINEA,

    -- Transacciones acumuladas por MOB (1M a 24M)
    COALESCE(cmp.NUM_CMP_LTD_1M, 0) AS NUM_CMP_LTD_1M,
    COALESCE(cmp.NUM_CMP_LTD_2M, 0) AS NUM_CMP_LTD_2M,
    COALESCE(cmp.NUM_CMP_LTD_3M, 0) AS NUM_CMP_LTD_3M,
    COALESCE(cmp.NUM_CMP_LTD_4M, 0) AS NUM_CMP_LTD_4M,
    COALESCE(cmp.NUM_CMP_LTD_5M, 0) AS NUM_CMP_LTD_5M,
    COALESCE(cmp.NUM_CMP_LTD_6M, 0) AS NUM_CMP_LTD_6M,
    COALESCE(cmp.NUM_CMP_LTD_7M, 0) AS NUM_CMP_LTD_7M,
    COALESCE(cmp.NUM_CMP_LTD_8M, 0) AS NUM_CMP_LTD_8M,
    COALESCE(cmp.NUM_CMP_LTD_9M, 0) AS NUM_CMP_LTD_9M,
    COALESCE(cmp.NUM_CMP_LTD_10M, 0) AS NUM_CMP_LTD_10M,
    COALESCE(cmp.NUM_CMP_LTD_11M, 0) AS NUM_CMP_LTD_11M,
    COALESCE(cmp.NUM_CMP_LTD_12M, 0) AS NUM_CMP_LTD_12M,
    COALESCE(cmp.NUM_CMP_LTD_13M, 0) AS NUM_CMP_LTD_13M,
    COALESCE(cmp.NUM_CMP_LTD_14M, 0) AS NUM_CMP_LTD_14M,
    COALESCE(cmp.NUM_CMP_LTD_15M, 0) AS NUM_CMP_LTD_15M,
    COALESCE(cmp.NUM_CMP_LTD_16M, 0) AS NUM_CMP_LTD_16M,
    COALESCE(cmp.NUM_CMP_LTD_17M, 0) AS NUM_CMP_LTD_17M,
    COALESCE(cmp.NUM_CMP_LTD_18M, 0) AS NUM_CMP_LTD_18M,
    COALESCE(cmp.NUM_CMP_LTD_19M, 0) AS NUM_CMP_LTD_19M,
    COALESCE(cmp.NUM_CMP_LTD_20M, 0) AS NUM_CMP_LTD_20M,
    COALESCE(cmp.NUM_CMP_LTD_21M, 0) AS NUM_CMP_LTD_21M,
    COALESCE(cmp.NUM_CMP_LTD_22M, 0) AS NUM_CMP_LTD_22M,
    COALESCE(cmp.NUM_CMP_LTD_23M, 0) AS NUM_CMP_LTD_23M,
    COALESCE(cmp.NUM_CMP_LTD_24M, 0) AS NUM_CMP_LTD_24M
  FROM SOLICITUDES sol
  INNER JOIN COMPORTAMIENTO_CUENTAS cmp
    ON sol.CTA_CVE = cmp.CTA_CVE
)

-- STREAMING_CHUNK:Generando la salida final agregada con el promedio de compras acumuladas a 24 meses...
-- ============================================================
-- OUTPUT FINAL: PROMEDIO DE COMPRAS ACUMULADAS AL CABO DE 2 AÑOS (Y EVOLUCIÓN MOB 1-24)
-- POR BURÓ HIT Y RANGO DE LÍNEA DE CRÉDITO
-- ============================================================
SELECT
  BR_HIT_DES,
  RANGO_LINEA,
  COUNT(DISTINCT CTA_CVE) AS TOTAL_CUENTAS,

  -- Promedio acumulado al cabo de 2 Años (MOB 24)
  -- ROUND(AVG(NUM_CMP_LTD_24M), 2) AS NUM_COMPRAS_PROM_24M_2ANOS,

  -- Evolución mes a mes para análisis de curva (MOB 1 a 23)
  ROUND(AVG(NUM_CMP_LTD_1M), 2)  AS NUM_COMPRAS_PROM_1M,
  -- ROUND(AVG(NUM_CMP_LTD_2M), 2)  AS NUM_COMPRAS_PROM_2M,
  -- ROUND(AVG(NUM_CMP_LTD_3M), 2)  AS NUM_COMPRAS_PROM_3M,
  -- ROUND(AVG(NUM_CMP_LTD_4M), 2)  AS NUM_COMPRAS_PROM_4M,
  -- ROUND(AVG(NUM_CMP_LTD_5M), 2)  AS NUM_COMPRAS_PROM_5M,
  ROUND(AVG(NUM_CMP_LTD_6M), 2)  AS NUM_COMPRAS_PROM_6M,
  -- ROUND(AVG(NUM_CMP_LTD_7M), 2)  AS NUM_COMPRAS_PROM_7M,
  -- ROUND(AVG(NUM_CMP_LTD_8M), 2)  AS NUM_COMPRAS_PROM_8M,
  -- ROUND(AVG(NUM_CMP_LTD_9M), 2)  AS NUM_COMPRAS_PROM_9M,
  -- ROUND(AVG(NUM_CMP_LTD_10M), 2) AS NUM_COMPRAS_PROM_10M,
  -- ROUND(AVG(NUM_CMP_LTD_11M), 2) AS NUM_COMPRAS_PROM_11M,
  ROUND(AVG(NUM_CMP_LTD_12M), 2) AS NUM_COMPRAS_PROM_12M,
  -- ROUND(AVG(NUM_CMP_LTD_13M), 2) AS NUM_COMPRAS_PROM_13M,
  -- ROUND(AVG(NUM_CMP_LTD_14M), 2) AS NUM_COMPRAS_PROM_14M,
  -- ROUND(AVG(NUM_CMP_LTD_15M), 2) AS NUM_COMPRAS_PROM_15M,
  -- ROUND(AVG(NUM_CMP_LTD_16M), 2) AS NUM_COMPRAS_PROM_16M,
  -- ROUND(AVG(NUM_CMP_LTD_17M), 2) AS NUM_COMPRAS_PROM_17M,
  -- ROUND(AVG(NUM_CMP_LTD_18M), 2) AS NUM_COMPRAS_PROM_18M,
  -- ROUND(AVG(NUM_CMP_LTD_19M), 2) AS NUM_COMPRAS_PROM_19M,
  -- ROUND(AVG(NUM_CMP_LTD_20M), 2) AS NUM_COMPRAS_PROM_20M,
  -- ROUND(AVG(NUM_CMP_LTD_21M), 2) AS NUM_COMPRAS_PROM_21M,
  -- ROUND(AVG(NUM_CMP_LTD_22M), 2) AS NUM_COMPRAS_PROM_22M,
  -- ROUND(AVG(NUM_CMP_LTD_23M), 2) AS NUM_COMPRAS_PROM_23M

FROM CONSOLIDADO
WHERE BR_HIT_DES IN ('HIT', 'NOHIT')
GROUP BY 1, 2
ORDER BY BR_HIT_DES, RANGO_LINEA;
